shortcut.rename-session = ctrl + ~
shortcut.previous-session = ctrl + (
shortcut.next-session = ctrl + )
shortcut.close-session = ctrl + q
shortcut.create-session = ctrl + \`
extra-keys = []
fullscreen = true
